# Env
language: python
python:
  - "2.6"
  - "2.7"

# Dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"

# Test
script: nosetests

# Coverage
after_success:
  - "pip install python-coveralls"
  - coveralls
