# Env
language: python

python:
  - 2.6
  - 2.7

services:
  - redis-server

# Dependencies
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage
  - if [[ $TRAVIS_PYTHON_VERSION != '2.5' ]]; then pip install coveralls --use-mirrors && export HAS_COVERALLS=1; fi

# Test
script:
  - nosetests --with-coverage --cover-package=tidehunter
  - chmod 755 deploy
  - ./deploy
  - ./deploy -u
  - pip uninstall tidehunter -yq

# Coverage
after_success:
  - if [[ $HAS_COVERALLS ]]; then coveralls; fi
